# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/XILINX/EchoSmall/EchoSmall.cache/wt [current_project]
set_property parent.project_path G:/XILINX/EchoSmall/EchoSmall.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths c:/Xilinx/Downloads/vivadoIPLib/ip [current_project]
set_property ip_output_repo g:/XILINX/EchoSmall/EchoSmall.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib G:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/hdl/BaseSystem_wrapper.v
add_files G:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/BaseSystem.bd
set_property used_in_implementation false [get_files -all g:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all G:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/BaseSystem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/XILINX/EchoSmall/EchoSmall.srcs/constrs_1/new/ArtyZ7.xdc
set_property used_in_implementation false [get_files G:/XILINX/EchoSmall/EchoSmall.srcs/constrs_1/new/ArtyZ7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top BaseSystem_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BaseSystem_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BaseSystem_wrapper_utilization_synth.rpt -pb BaseSystem_wrapper_utilization_synth.pb"
