# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BaseSystem/BaseSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BaseSystem || ORIG_REF_NAME==BaseSystem} -quiet] -quiet

# IP: bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BaseSystem_processing_system7_0_0 || ORIG_REF_NAME==BaseSystem_processing_system7_0_0} -quiet] -quiet

# XDC: bd/BaseSystem/BaseSystem_ooc.xdc
