# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xci
# IP: The module: 'BaseSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BaseSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xci
# IP: The module: 'BaseSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/XILINX/EchoSmall/EchoSmall.srcs/sources_1/bd/BaseSystem/ip/BaseSystem_processing_system7_0_0/BaseSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BaseSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
