
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SSI_Reader_Test(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// EEPROM //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// 2x13 GPIO Header //////////
	inout 		    [12:0]		GPIO_2,
	input 		     [2:0]		GPIO_2_IN,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [33:0]		GPIOH0,
	input 		     [1:0]		GPIOH0_IN,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [33:0]		GPIOH1,
	input 		     [1:0]		GPIOH1_IN
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	localparam RESOLUTION = 10;
	
	//SSI Wires/Regs
	wire NCS, SSI_DataLine, SSI_CLK;
	wire [RESOLUTION-1:0] SSI_DataOut;
	
	
	//UART Wires/Regs
	wire SSI_DataValid = 1'b1;

	reg [7:0] data_in_reg;
   wire [7:0] data_in, data_out;
   wire data_in_ready, data_out_valid, data_out_ready;
	wire rst, FPGA_SERIAL_RX, FPGA_SERIAL_TX;
	
	//I/O assignments:
	assign GPIOH0[0] = FPGA_SERIAL_TX; //writes to pin0
	assign FPGA_SERIAL_RX = GPIOH0[1]; //reads pin1
	
	assign GPIOH0[3] = NCS;
	assign GPIOH0[5] = SSI_CLK ;
	assign SSI_DataLine = GPIOH0[7];
	
	//UART assignments:
	assign data_in = SSI_DataOut[7:0];
	assign LED = SSI_DataOut[7:0];

//=======================================================
//  Structural coding
//=======================================================


	SSI_Reader #(
		.RES(RESOLUTION)
	) Read_SSI(
		.clk(CLOCK_50),
		.DataIn(SSI_DataLine),
		.magHIGH(),
		.magLOW(),
		.SSI_CLK(SSI_CLK),
		.NCS(NCS),
		.DataOut(SSI_DataOut),
		.Poll_test()
		
	);

	 uart # (
        .CLOCK_FREQ(50_000_000),
        .BAUD_RATE(9600)
    ) on_chip_uart (
        .clk(CLOCK_50),
        .reset(rst),
        .data_in(data_in),
        .data_in_valid(SSI_DataValid),
        .data_in_ready(data_in_ready),
        .data_out(data_out),
        .data_out_valid(data_out_valid),
        .data_out_ready(data_out_ready),
        .serial_in(FPGA_SERIAL_RX),
        .serial_out(FPGA_SERIAL_TX)
    );
endmodule