webtalk_init -webtalk_dir G:\\XILINX\\RoverClient\\RoverClient_FPGA.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-03-08 19:03:19" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211444376_1777530152_210669633_446" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "68a0v6b7l6qj8er0um45i4udp9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.3_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8350 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4013 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.268 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1520493476417" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.3.1" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1520493476417"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key BootgenCount -value "7" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key FlashCount -value "6" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1520564599184"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1520564599184"
webtalk_transmit -clientid 1637762707 -regid "211444376_1777530152_210669633_446" -xml G:\\XILINX\\RoverClient\\RoverClient_FPGA.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html G:\\XILINX\\RoverClient\\RoverClient_FPGA.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm G:\\XILINX\\RoverClient\\RoverClient_FPGA.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
